# -*- coding: utf-8 -*-
VMAX_KMH = 110.0
LIMITE_DIST_MIN_KM = 1.0
VMAX_CURTA_KMH = 3600.0
DIST_MAX_ALTERNATIVA_KM = 10.0
DIST_SPIKE_CAUDA_INICIAL_KM = 3.0
DIST_RETORNO_SPIKE_CAUDA_INICIAL_KM = 1.0
JANELA_RETORNO_SPIKE_CAUDA_MIN = 30.0
CUSTO_INVIAVEL = 1e12
RAZAO_CLAREZA_INSERCAO = 1.50
DIF_CLAREZA_INSERCAO_KM = 3.0